import { Recipe } from '@/features/recipes/types';

/** Mock authors for sample data */
const AUTHORS = {
  minh: { id: 'a1', name: 'Chef Minh', avatarUrl: 'https://i.pravatar.cc/100?u=minh' },
  lan: { id: 'a2', name: 'Bếp Lan', avatarUrl: 'https://i.pravatar.cc/100?u=lan' },
  hoa: { id: 'a3', name: 'Hoa Kitchen', avatarUrl: 'https://i.pravatar.cc/100?u=hoa' },
  tuan: { id: 'a4', name: 'Tuấn Cook', avatarUrl: 'https://i.pravatar.cc/100?u=tuan' },
  mai: { id: 'a5', name: 'Mai Nguyễn', avatarUrl: 'https://i.pravatar.cc/100?u=mai' },
};

/** 15 mock recipes with Vietnamese food focus */
export const MOCK_RECIPES: Recipe[] = [
  {
    id: '1',
    title: 'Phở Bò Hà Nội',
    description:
      'Phở bò truyền thống với nước dùng ninh xương 12 tiếng, bánh phở tươi và thịt bò tái.',
    imageUrl: 'https://picsum.photos/seed/pho/800/450',
    cookTime: 180,
    difficulty: 'Hard',
    category: 'Dinner',
    author: AUTHORS.minh,
    likeCount: 342,
    isBookmarked: false,
    isFeatured: true,
    createdAt: '2026-03-15T08:00:00Z',
  },
  {
    id: '2',
    title: 'Bánh Mì Thịt Nướng',
    description: 'Bánh mì giòn với thịt heo nướng sả, đồ chua và rau thơm.',
    imageUrl: 'https://picsum.photos/seed/banhmi/800/450',
    cookTime: 45,
    difficulty: 'Medium',
    category: 'Lunch',
    author: AUTHORS.lan,
    likeCount: 256,
    isBookmarked: true,
    isFeatured: true,
    createdAt: '2026-03-14T10:00:00Z',
  },
  {
    id: '3',
    title: 'Cơm Tấm Sườn Bì Chả',
    description: 'Cơm tấm Sài Gòn với sườn nướng, bì và chả trứng.',
    imageUrl: 'https://picsum.photos/seed/comtam/800/450',
    cookTime: 60,
    difficulty: 'Medium',
    category: 'Lunch',
    author: AUTHORS.hoa,
    likeCount: 189,
    isBookmarked: false,
    isFeatured: true,
    createdAt: '2026-03-13T12:00:00Z',
  },
  {
    id: '4',
    title: 'Bún Chả Hà Nội',
    description: 'Bún chả với thịt nướng than hoa, nước mắm pha và rau sống.',
    imageUrl: 'https://picsum.photos/seed/buncha/800/450',
    cookTime: 50,
    difficulty: 'Medium',
    category: 'Lunch',
    author: AUTHORS.tuan,
    likeCount: 421,
    isBookmarked: false,
    isFeatured: true,
    createdAt: '2026-03-12T09:00:00Z',
  },
  {
    id: '5',
    title: 'Gỏi Cuốn Tôm Thịt',
    description: 'Gỏi cuốn tươi mát với tôm, thịt heo luộc, bún và rau sống.',
    imageUrl: 'https://picsum.photos/seed/goicuon/800/450',
    cookTime: 30,
    difficulty: 'Easy',
    category: 'Snack',
    author: AUTHORS.mai,
    likeCount: 178,
    isBookmarked: false,
    isFeatured: false,
    createdAt: '2026-03-11T14:00:00Z',
  },
  {
    id: '6',
    title: 'Chè Ba Màu',
    description: 'Chè ba màu truyền thống với đậu đỏ, đậu xanh và thạch lá dứa.',
    imageUrl: 'https://picsum.photos/seed/chebamau/800/450',
    cookTime: 90,
    difficulty: 'Medium',
    category: 'Dessert',
    author: AUTHORS.lan,
    likeCount: 134,
    isBookmarked: true,
    isFeatured: false,
    createdAt: '2026-03-10T16:00:00Z',
  },
  {
    id: '7',
    title: 'Cà Phê Sữa Đá',
    description: 'Cà phê phin truyền thống Việt Nam với sữa đặc và đá.',
    imageUrl: 'https://picsum.photos/seed/caphe/800/450',
    cookTime: 10,
    difficulty: 'Easy',
    category: 'Drink',
    author: AUTHORS.tuan,
    likeCount: 298,
    isBookmarked: false,
    isFeatured: false,
    createdAt: '2026-03-09T07:00:00Z',
  },
  {
    id: '8',
    title: 'Canh Chua Cá Lóc',
    description: 'Canh chua miền Tây với cá lóc, thơm, cà chua và rau ngổ.',
    imageUrl: 'https://picsum.photos/seed/canhchua/800/450',
    cookTime: 40,
    difficulty: 'Easy',
    category: 'Dinner',
    author: AUTHORS.hoa,
    likeCount: 156,
    isBookmarked: false,
    isFeatured: false,
    createdAt: '2026-03-08T18:00:00Z',
  },
  {
    id: '9',
    title: 'Xôi Xéo Hà Nội',
    description: 'Xôi xéo với đậu xanh, hành phi và mỡ hành.',
    imageUrl: 'https://picsum.photos/seed/xoixeo/800/450',
    cookTime: 60,
    difficulty: 'Medium',
    category: 'Breakfast',
    author: AUTHORS.minh,
    likeCount: 87,
    isBookmarked: false,
    isFeatured: false,
    createdAt: '2026-03-07T06:00:00Z',
  },
  {
    id: '10',
    title: 'Bánh Xèo Miền Tây',
    description: 'Bánh xèo giòn rụm với tôm, thịt, giá đỗ và nước mắm chua ngọt.',
    imageUrl: 'https://picsum.photos/seed/banhxeo/800/450',
    cookTime: 35,
    difficulty: 'Easy',
    category: 'Dinner',
    author: AUTHORS.mai,
    likeCount: 213,
    isBookmarked: true,
    isFeatured: false,
    createdAt: '2026-03-06T19:00:00Z',
  },
  {
    id: '11',
    title: 'Rau Câu Dừa',
    description: 'Rau câu lá dứa nước cốt dừa mát lịm cho ngày hè.',
    imageUrl: 'https://picsum.photos/seed/raucau/800/450',
    cookTime: 45,
    difficulty: 'Easy',
    category: 'Dessert',
    author: AUTHORS.lan,
    likeCount: 98,
    isBookmarked: false,
    isFeatured: false,
    createdAt: '2026-03-05T15:00:00Z',
  },
  {
    id: '12',
    title: 'Đậu Hũ Sốt Cà Chua',
    description: 'Đậu hũ chiên giòn sốt cà chua đơn giản, phù hợp ăn chay.',
    imageUrl: 'https://picsum.photos/seed/dauhu/800/450',
    cookTime: 25,
    difficulty: 'Easy',
    category: 'Vegetarian',
    author: AUTHORS.hoa,
    likeCount: 145,
    isBookmarked: false,
    isFeatured: false,
    createdAt: '2026-03-04T12:00:00Z',
  },
  {
    id: '13',
    title: 'Tôm Rang Muối',
    description: 'Tôm rang muối ớt giòn tan, ăn kèm cơm nóng.',
    imageUrl: 'https://picsum.photos/seed/tomrang/800/450',
    cookTime: 20,
    difficulty: 'Easy',
    category: 'Seafood',
    author: AUTHORS.tuan,
    likeCount: 267,
    isBookmarked: false,
    isFeatured: false,
    createdAt: '2026-03-03T20:00:00Z',
  },
  {
    id: '14',
    title: 'Bánh Cuốn Thanh Trì',
    description: 'Bánh cuốn nóng mỏng mịn với nhân thịt và nước mắm chua ngọt.',
    imageUrl: 'https://picsum.photos/seed/banhcuon/800/450',
    cookTime: 70,
    difficulty: 'Hard',
    category: 'Breakfast',
    author: AUTHORS.minh,
    likeCount: 176,
    isBookmarked: false,
    isFeatured: false,
    createdAt: '2026-03-02T07:00:00Z',
  },
  {
    id: '15',
    title: 'Sinh Tố Bơ',
    description: 'Sinh tố bơ béo ngậy với sữa đặc và đá xay.',
    imageUrl: 'https://picsum.photos/seed/sinhto/800/450',
    cookTime: 5,
    difficulty: 'Easy',
    category: 'Drink',
    author: AUTHORS.mai,
    likeCount: 312,
    isBookmarked: true,
    isFeatured: false,
    createdAt: '2026-03-01T10:00:00Z',
  },
];
