spring:
  application:
    name: cookmate
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/cookmate}

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /

management:
  endpoints:
    web:
      exposure:
        include: health,info
